[package]
name = "adventofcode-2024"
version = "0.1.0"
edition = "2021"

[profile.profiling]
inherits = "release"
debug = true

[[bin]]
name = "day01"

[dependencies]
winnow = "0.6"

[dev-dependencies]
rstest = "0.23"
